import type { Metadata } from 'next';
import '@/shared/styles/globals.css';

// TODO: metadata 수정하기
export const metadata: Metadata = {
  title: '글로벌노마드: global nomad',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>{children}</body>
    </html>
  );
}
